# Generated by Django 5.2.7 on 2025-10-30 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='blood_reports/')),
                ('extracted_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllergyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mentioned_allergies', models.TextField(blank=True, help_text='Allergies mentioned by user')),
                ('common_allergies_response', models.JSONField(default=dict, help_text='Responses to common allergies')),
                ('blood_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_info', to='analyzer.bloodreport')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods_to_eat', models.TextField()),
                ('foods_to_avoid', models.TextField()),
                ('daily_habits', models.TextField()),
                ('detailed_analysis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='analyzer.bloodreport')),
            ],
        ),
    ]
