# Generated by Django 5.2.7 on 2025-11-04 06:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_bloodreport_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_text', models.CharField(help_text='The habit being tracked', max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about progress')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_progress', to='analyzer.bloodreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'habit_text'],
                'unique_together': {('blood_report', 'habit_text', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProgressStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, help_text='Current consecutive days')),
                ('longest_streak', models.IntegerField(default=0, help_text='Longest streak achieved')),
                ('total_habits_completed', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(default=django.utils.timezone.now)),
                ('blood_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='analyzer.bloodreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'blood_report')},
            },
        ),
    ]
