# Generated by Django 6.0 on 2026-01-05 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_habitprogress_progressstreak'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CBC', 'Complete Blood Count'), ('DIFF', 'Differential Count')], max_length=10)),
                ('common_names', models.CharField(help_text='Comma-separated aliases like Hb,HGB', max_length=200)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('normal_min', models.FloatField(blank=True, null=True)),
                ('normal_max', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodReportValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.bloodparameter')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.bloodreport')),
            ],
        ),
    ]
